# Challenge 1

In this challenge you will be working on **pokemons**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](pokemon.jpg)

Follow the instructions below and enter your code.

### Import all required libraries

In [97]:
# import libraries
import pandas as pd
import numpy as np

### Import data set

Import data set `Pokemon.csv` from the `your-code` directory of this lab. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [98]:
# import data set
pokemon = pd.read_csv('/Users/anielkaaslan/Documents/data-labs/module-2/lab-df-calculation-and-transformation/your-code/Pokemon.csv')

### Print first 10 rows of `pokemon`

In [99]:
# enter your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

### Obtain the distinct values across `Type 1` and `Type 2`

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [100]:
# enter your code here
values = pokemon[['Type 1', 'Type 2']]
values
np.array(values)

array([['Grass', 'Poison'],
       ['Grass', 'Poison'],
       ['Grass', 'Poison'],
       ...,
       ['Psychic', 'Ghost'],
       ['Psychic', 'Dark'],
       ['Fire', 'Water']], dtype=object)

### Cleanup `Name` that contain "Mega"

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [101]:
# enter your code here
# pokemon[pokemon['Name'].str.contains('Mega')]
pokemon = pd.read_csv('Pokemon.csv')
poke = pokemon['Name'].str.replace('Mega', ' Mega')
poke = poke.str.split()
poke = [i[1:] if 'Mega' in i else i for i in poke]
pokemon['Name'] = [' '.join(i) for i in poke]
pokemon['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3              Mega Venusaur
4                 Charmander
5                 Charmeleon
6                  Charizard
7           Mega Charizard X
8           Mega Charizard Y
9                   Squirtle
10                 Wartortle
11                 Blastoise
12            Mega Blastoise
13                  Caterpie
14                   Metapod
15                Butterfree
16                    Weedle
17                    Kakuna
18                  Beedrill
19             Mega Beedrill
20                    Pidgey
21                 Pidgeotto
22                   Pidgeot
23              Mega Pidgeot
24                   Rattata
25                  Raticate
26                   Spearow
27                    Fearow
28                     Ekans
29                     Arbok
               ...
770                  Sylveon
771                 Hawlucha
772                  Dedenne
773                  Carbink
774                    Goomy
775                  Sliggoo
776                   Goodra
777                   Klefki
778                 Phantump
779                Trevenant
780    PumpkabooAverage Size
781      PumpkabooSmall Size
782      PumpkabooLarge Size
783      PumpkabooSuper Size
784    GourgeistAverage Size
785      GourgeistSmall Size
786      GourgeistLarge Size
787      GourgeistSuper Size
788                 Bergmite
789                  Avalugg
790                   Noibat
791                  Noivern
792                  Xerneas
793                  Yveltal
794         Zygarde50% Forme
795                  Diancie
796             Mega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [102]:
# enter your code here
pokemon['A/D Ratio'] = pokemon['Attack'] / pokemon['Defense']
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,1.103448
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,0.738462

### Identify the pokemon with the highest `A/D Ratio`

In [103]:
# enter your code here
# pokemon['A/D Ratio'].max()
pokemon.loc[pokemon['A/D Ratio'].idxmax()]

#                            386
Name          DeoxysAttack Forme
Type 1                   Psychic
Type 2                       NaN
Total                        600
HP                            50
Attack                       180
Defense                       20
Sp. Atk                      180
Sp. Def                       20
Speed                        150
Generation                     3
Legendary                   True
A/D Ratio                      9
Name: 429, dtype: object

### Identify the pokemon with the lowest A/D Ratio

In [104]:
# enter your code here

# pokemon['A/D Ratio'].min()
pokemon.loc[pokemon['A/D Ratio'].idxmin()]

#                   213
Name            Shuckle
Type 1              Bug
Type 2             Rock
Total               505
HP                   20
Attack               10
Defense             230
Sp. Atk              10
Sp. Def             230
Speed                 5
Generation            2
Legendary         False
A/D Ratio     0.0434783
Name: 230, dtype: object

### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [138]:
# enter your code here


pokemon['Combo Type'] = np.where(
    pokemon['Type 2'].isnull(),
    np.concatenate([pokemon['Type 1'], pokemon['Type 2']]),#'Type 1', 'Type 2'
    pokemon['Type 1'])
                   
pokemon['Combo Type']

ValueError: operands could not be broadcast together with shapes (800,) (1600,) (800,)

### Identify the pokemons whose `A/D Ratio` are among the top 5

In [116]:
# enter your code here
# pokemon.nlargest(5, columns=['A/D Ratio']) #this works too
pokemon.sort_values('A/D Ratio',ascending=False).iloc[:5,]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,NaN
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,NaN
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water

### For the 5 pokemons printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemons with the highest `A/D Ratio`.

In [119]:
# enter your code here
df2 = pokemon.sort_values('A/D Ratio',ascending=False).iloc[:5,]
df2['Combo Type'] = list(np.where(
    df2['Type 2'].isnull(),
    (df2['Type 1'] + df2['Type 2']), 
    df2['Type 1']))
df2

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,NaN
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,NaN
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water

### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemons.

Your output should look like below:

![Aggregate](aggregated-mean.png)

In [124]:
# enter your code here
pokemon.groupby('Combo Type').mean()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Combo Type,,,,,,,,,,,
Bug,325.711538,408.096154,58.134615,77.711538,75.730769,58.634615,71.711538,66.173077,3.134615,0.000000,1.129359
Dark,486.333333,450.285714,69.809524,88.190476,74.523810,71.476190,73.238095,73.047619,4.142857,0.047619,1.298858
Dragon,455.857143,622.380952,94.571429,122.571429,96.476190,116.238095,97.857143,94.666667,3.714286,0.571429,1.292674
Electric,458.058824,490.823529,59.470588,68.882353,83.764706,108.882353,85.352941,84.470588,3.882353,0.176471,0.882953
Fairy,322.000000,475.000000,70.000000,45.000000,90.000000,100.000000,110.000000,60.000000,3.000000,0.000000,0.498452
Fighting,456.428571,477.857143,66.142857,95.857143,75.142857,82.571429,69.857143,88.285714,4.142857,0.000000,1.248473
Fire,384.541667,511.583333,78.291667,92.166667,78.708333,105.458333,80.166667,76.791667,3.708333,0.166667,1.235233
Flying,714.500000,390.000000,62.500000,50.000000,57.500000,71.000000,60.000000,89.000000,6.000000,0.000000,0.866071
Ghost,525.681818,444.090909,71.318182,72.545455,78.090909,82.045455,70.590909,69.500000,4.500000,0.090909,0.994578
Grass,298.567568,436.810811,69.837838,77.135135,71.135135,81.243243,75.351351,62.108108,2.918919,0.054054,1.135574
Ground,443.894737,466.421053,80.000000,101.315789,86.263158,62.421053,67.578947,68.842105,3.789474,0.157895,1.268726
Ice,292.272727,419.090909,76.818182,69.090909,61.363636,75.000000,69.090909,67.727273,2.454545,0.090909,1.210426
Normal,322.297297,390.675676,70.972973,72.972973,57.540541,56.432432,57.756757,75.000000,3.162162,0.000000,1.340928
Poison,336.692308,422.076923,68.692308,77.461538,70.615385,63.923077,67.307692,74.076923,3.230769,0.000000,1.155926
Psychic,378.473684,498.736842,66.789474,84.473684,68.578947,98.105263,94.052632,86.736842,3.473684,0.263158,1.226221
Rock,388.257143,465.142857,64.914286,90.171429,99.142857,69.200000,79.885714,61.828571,3.342857,0.085714,1.024504
Steel,430.545455,486.272727,65.954545,93.318182,125.090909,68.318182,78.045455,55.545455,3.772727,0.136364,0.830285
Water,303.320755,449.056604,77.867925,76.735849,77.113208,76.886792,76.622642,63.830189,2.849057,0.018868,1.093557